// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsuwqknrixlbuhqtkckd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdXdxa25yaXhsYnVocXRrY2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NzY1OTMsImV4cCI6MjA1MzE1MjU5M30.FiHpR4CXVr2JdJD1eFUL23wX-f2YMA81_xJlApf_9Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);